SPRITE jetman_sprite "sprite/jetman.png" 2 4 NONE 0
SPRITE carl_sprite "sprite/jetman_carl.png" 2 4 NONE 0
SPRITE ann_sprite "sprite/jetman_ann.png" 2 4 NONE 0
SPRITE shot_sprite "sprite/shot.png" 3 1 NONE 0
SPRITE u1_base_sprite "sprite/u1_base.png" 2 2 NONE 0
SPRITE u1_middle_sprite "sprite/u1_middle.png" 2 2 NONE 0
SPRITE u1_top_sprite "sprite/u1_top.png" 2 2 NONE 0
SPRITE u1_sprite "sprite/u1.png" 2 6 NONE 0
SPRITE u2_base_sprite "sprite/u2_base.png" 2 2 NONE 0
SPRITE u2_middle_sprite "sprite/u2_middle.png" 2 2 NONE 0
SPRITE u2_top_sprite "sprite/u2_top.png" 2 2 NONE 0
SPRITE u2_sprite "sprite/u2.png" 2 6 NONE 0
SPRITE u3_base_sprite "sprite/u3_base.png" 2 2 NONE 0
SPRITE u3_middle_sprite "sprite/u3_middle.png" 2 2 NONE 0
SPRITE u3_top_sprite "sprite/u3_top.png" 2 2 NONE 0
SPRITE u3_sprite "sprite/u3.png" 2 6 NONE 0
SPRITE u4_base_sprite "sprite/u4_base.png" 2 2 NONE 0
SPRITE u4_middle_sprite "sprite/u4_middle.png" 2 2 NONE 0
SPRITE u4_top_sprite "sprite/u4_top.png" 2 2 NONE 0
SPRITE u4_sprite "sprite/u4.png" 2 6 NONE 0
SPRITE fire_sprite "sprite/fire.png" 2 2 NONE 5
SPRITE meteorite_sprite "sprite/meteorite.png" 2 2 NONE 0
SPRITE alien_sprite "sprite/alien.png" 2 2 NONE 0
SPRITE bubble_sprite "sprite/bubble.png" 2 2 NONE 20
SPRITE fighter_sprite "sprite/fighter.png" 2 1 NONE 0
SPRITE saucer_sprite "sprite/saucer.png" 2 1 NONE 0
SPRITE falcon_sprite "sprite/falcon.png" 2 2 NONE 0
SPRITE cross_sprite "sprite/cross.png" 2 2 NONE 0
SPRITE owl_sprite "sprite/owl.png" 2 2 NONE 0
SPRITE boom_sprite "sprite/boom.png" 3 2 NONE 0
SPRITE fuel_sprite "sprite/fuel.png" 2 2 NONE 0
SPRITE gold_sprite "sprite/gold.png" 2 1 NONE 0
SPRITE nuke_sprite "sprite/nuke.png" 2 2 NONE 15
SPRITE triatom_sprite "sprite/triatom.png" 2 2 NONE 15
SPRITE bean_sprite "sprite/bean.png" 2 2 NONE 0
SPRITE diamond_sprite "sprite/diamond.png" 2 2 NONE 5
SPRITE cursor_sprite "sprite/cursor.png" 1 1 NONE 0
