SPRITE jetman_sprite "sprite/jetman.png" 2 4 FAST 0
SPRITE enemy_01_sprite "sprite/enemy_01.png" 2 2 FAST 0
SPRITE enemy_02_sprite "sprite/enemy_02.png" 2 2 FAST 0
SPRITE u1_base_sprite "sprite/u1_base.png" 2 2 FAST 0
SPRITE u1_middle_sprite "sprite/u1_middle.png" 2 2 FAST 0
SPRITE u1_top_sprite "sprite/u1_top.png" 2 2 FAST 0
SPRITE u1_sprite "sprite/u1.png" 2 6 FAST 0
SPRITE fuel_sprite "sprite/fuel.png" 2 2 FAST 0
SPRITE boom_sprite "sprite/boom.png" 3 2 FAST 0
SPRITE cursor_sprite "sprite/cursor.png" 1 1 FAST 0
